FROM alpine:3.12.1

ENV TERRAFORM_VERSION=0.12.24

# Dependencies. #Terraform # Awscli # make directory
RUN apk update && \
    apk add curl jq python3 py3-pip bash ca-certificates git openssl unzip wget openssh-keygen && \
    cd /tmp && \
    wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin && \
    pip3 install awscli && pip3 install requests urllib3 && pip3 install git+git://github.com/HR/github-clone#egg=ghclone && \
    rm -rf /tmp/* && \
    rm -rf /var/cache/apk/* && \
    rm -rf /var/tmp/*

# Aviatrix Kickstart.
ADD     kickstart/controller /root/controller
ADD     kickstart/controller-govcloud /root/controller-govcloud
ADD	kickstart/mcna /root/mcna
ADD	kickstart/mcna-govcloud /root/mcna-govcloud
ADD	kickstart/kickstart.sh /root/
ADD	kickstart/.plane /root/
ADD	kickstart/.eagle /root/

# Kickstart backend.
ADD	kickstart/kickstart_web.sh /root/
ADD kickstart-backend/requirements.txt /root/requirements.txt
RUN pip3 install -r /root/requirements.txt 
ADD kickstart-backend /root/

# Misc. configuration
RUN	mkdir -p /root/.emacs.d/lisp
ADD	config/terraform-mode.el /root/.emacs.d/lisp
ADD	config/hcl-mode.el /root/.emacs.d/lisp
ADD	config/dotemacs /root/.emacs

WORKDIR /root
CMD python3 app.py

# Run Kickstart when starting container
# RUN	echo '[ -f /root/.kickstart_restore ] && source /root/.kickstart_restore' >> ~/.bashrc && \
#     echo 'source /root/kickstart.sh' >> ~/.bashrc
