FROM phusion/baseimage:0.10.1

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# Dependencies.
RUN	apt-get -y update && \
	apt-get -y install wget unzip emacs python3-pip sysvbanner screen

# Awscli.
RUN	wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -P /tmp
RUN	unzip /tmp/awscli-exe-linux-x86_64.zip -d /tmp
RUN	/tmp/aws/install

# Python libraries.
RUN	pip3 install requests urllib3

# Terraform.
RUN	wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip -P /tmp
RUN	unzip /tmp/terraform_0.12.24_linux_amd64.zip -d /usr/local/sbin/

# Aviatrix Kickstart.
ADD     kickstart/controller /root/controller
ADD	kickstart/mcna /root/mcna
ADD	kickstart/kickstart.sh /root/
ADD	kickstart/.plane /root/

# Misc. configuration
RUN	mkdir -p /root/.emacs.d/lisp
ADD	config/terraform-mode.el /root/.emacs.d/lisp
ADD	config/hcl-mode.el /root/.emacs.d/lisp
ADD	config/dotemacs /root/.emacs

# Run Kickstart when starting container
RUN	echo 'source /root/.kickstart_restore' >> ~/.bashrc
RUN	echo 'source /root/kickstart.sh' >> ~/.bashrc

# Clean up when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
